#!/bin/zsh

getOs() {
  local os
  case "$(uname -s)" in
    Darwin)
      os="darwin"
      ;;
    Linux)
      if [ -f /etc/os-release ]; then
        source /etc/os-release
        case "$ID" in
          ubuntu)
            os="ubuntu"
            ;;
          debian)
            os="debian"
            ;;
          *)
            os="unknown"
            return 1
            ;;
        esac
      else
        os="unknown"
        return 1
      fi
      ;;
    *)
      os="unknown"
      return 1
      ;;
  esac
  echo $os
}